dropdownElements = {
        'Director': ['Director de la Unidad Academica'],
        'Sub-director':['Subdirector Academico',
                        'Subdirector Administrativo',
                        'Subdirector De Servicios Educativos E Integracion Social'],
        'Jefe de Departamento':['Jefe de la Unidad de Informatica',
                                'JEfe de la seccion de estudios de posgrado e investigacion',
                                'Jefe del Departamento de Investigacion',
                                'Jefe del Departamente de Posgrado',
                                'Jefe del Laboratorio Institucional de la Red de Robotica y Mecatronica',
                                'Jefe del Departamento de Ciencias Basicas',
                                'Jefe del Departamento de Tecnologias Avanzadas',
                                'Jefe del Departamento de Formacion Integral e Institucional',
                                'Jefe del Departamento de Ingenieria',
                                'Jefe de la Unidad de Tecnologia Educativa y Campus Virtual',
                                'Jefe del Departamento de Evaluacion y Seguimiento Academico',
                                'Jefe del Departamento de Capital Humano',
                                'Jefe del Departamento de Recursos Financieros',
                                'Jefe del Departamento de Recursos Materiales y Servicios',
                                'Jefe del Departamento de Gestion Escolar',
                                'Jefe del Departamento de Servicios Estudiantiles',
                                'Jefa del Departamento de Extensión Y Apoyos Educativos']
}