dropdownElements = {
        'Funcionario':['Unidad Academica',
                       'Academico',
                        'Administrativo',
                        'SSEIS',
                        'Unidad de Informatica',
                        'SEPI',
                        'Investigacion',
                        'Departamento de Posgrado',
                        'Ciencias Basicas',
                        'Tecnologias Avanzadas',
                        'DFII',
                        'Ingenieria',
                        'UTEyCV',
                        'Evaluacion y Seguimiento Academico',
                        'Capital Humano',
                        'Recursos Financieros',
                        'Recursos Materiales y Servicios',
                        'Gestion Escolar',
                        'Servicios Estudiantiles',
                        'Extensión Y Apoyos Educativos',
                        'Visita',
                        'Congreso',
                        '...'],
        'Personal Administrativo':['Unidad Academica',
                       'Academico',
                        'Administrativo',
                        'SSEIS',
                        'Unidad de Informatica',
                        'SEPI',
                        'Investigacion',
                        'Departamento de Posgrado',
                        'Ciencias Basicas',
                        'Tecnologias Avanzadas',
                        'DFII',
                        'Ingenieria',
                        'UTEyCV',
                        'Evaluacion y Seguimiento Academico',
                        'Capital Humano',
                        'Recursos Financieros',
                        'Recursos Materiales y Servicios',
                        'Gestion Escolar',
                        'Servicios Estudiantiles',
                        'Extensión Y Apoyos Educativos',
                        'Visita',
                        'Congreso',
                        '...'],
        'Docente':['Unidad Academica',
                       'Academico',
                        'Administrativo',
                        'SSEIS',
                        'Unidad de Informatica',
                        'SEPI',
                        'Investigacion',
                        'Departamento de Posgrado',
                        'Ciencias Basicas',
                        'Tecnologias Avanzadas',
                        'DFII',
                        'Ingenieria',
                        'UTEyCV',
                        'Evaluacion y Seguimiento Academico',
                        'Capital Humano',
                        'Recursos Financieros',
                        'Recursos Materiales y Servicios',
                        'Gestion Escolar',
                        'Servicios Estudiantiles',
                        'Extensión Y Apoyos Educativos',
                        'Visita',
                        'Congreso',
                        '...'],
        'Técnico Docente':['Unidad Academica',
                       'Academico',
                        'Administrativo',
                        'SSEIS',
                        'Unidad de Informatica',
                        'SEPI',
                        'Investigacion',
                        'Departamento de Posgrado',
                        'Ciencias Basicas',
                        'Tecnologias Avanzadas',
                        'DFII',
                        'Ingenieria',
                        'UTEyCV',
                        'Evaluacion y Seguimiento Academico',
                        'Capital Humano',
                        'Recursos Financieros',
                        'Recursos Materiales y Servicios',
                        'Gestion Escolar',
                        'Servicios Estudiantiles',
                        'Extensión Y Apoyos Educativos',
                        'Visita',
                        'Congreso',
                        '...'],
        'Servicio Social':['Unidad Academica',
                       'Academico',
                        'Administrativo',
                        'SSEIS',
                        'Unidad de Informatica',
                        'SEPI',
                        'Investigacion',
                        'Departamento de Posgrado',
                        'Ciencias Basicas',
                        'Tecnologias Avanzadas',
                        'DFII',
                        'Ingenieria',
                        'UTEyCV',
                        'Evaluacion y Seguimiento Academico',
                        'Capital Humano',
                        'Recursos Financieros',
                        'Recursos Materiales y Servicios',
                        'Gestion Escolar',
                        'Servicios Estudiantiles',
                        'Extensión Y Apoyos Educativos',
                        'Visita',
                        'Congreso',
                        '...'],
        'Interinato':['Unidad Academica',
                       'Academico',
                        'Administrativo',
                        'SSEIS',
                        'Unidad de Informatica',
                        'SEPI',
                        'Investigacion',
                        'Departamento de Posgrado',
                        'Ciencias Basicas',
                        'Tecnologias Avanzadas',
                        'DFII',
                        'Ingenieria',
                        'UTEyCV',
                        'Evaluacion y Seguimiento Academico',
                        'Capital Humano',
                        'Recursos Financieros',
                        'Recursos Materiales y Servicios',
                        'Gestion Escolar',
                        'Servicios Estudiantiles',
                        'Extensión Y Apoyos Educativos',
                        'Visita',
                        'Congreso',
                        '...'],
}