dropdownElements = {
        'Director': ['Unidad Academica'],
        'Sub-director':['Academico',
                        'Administrativo',
                        'SSEIS',
                        '...'],
        'Jefe de Departamento':['Unidad de Informatica',
                                'SEPI',
                                'Investigacion',
                                'Posgrado',
                                'Ciencias Basicas',
                                'Tecnologias Avanzadas',
                                'DFII',
                                'Ingenieria',
                                'UTEyCV',
                                'Evaluacion y Seguimiento Academico',
                                'Capital Humano',
                                'Recursos Financieros',
                                'Recursos Materiales y Servicios',
                                'Gestion Escolar',
                                'Servicios Estudiantiles',
                                'Extensión Y Apoyos Educativos',
                                '...'],
        'Otros': ['Visita',
                  'Congreso',
                  '...']
}